/**
 * Amount provenance and date discipline (BR-06).
 *
 * Two rules this file exists to make structural:
 *
 *  1. **Actual, forecast and estimated amounts must stay visibly distinct.**
 *     A figure the user typed as a guess must never be presented with the same
 *     authority as one taken from a bank statement, so provenance travels with
 *     the amount rather than being inferred from context.
 *
 *  2. **Effective date and posting date are different facts.** A bill dated
 *     28 August entered on 4 September affects the August period but only became
 *     known in September. Conflating them silently rewrites closed periods.
 */
import type { IsoDate, IsoDateTime } from './common';

/**
 * Where an amount came from.
 * - `actual`    — evidenced by a statement, invoice or receipt.
 * - `forecast`  — generated by a schedule or model (e.g. an expected charge).
 * - `estimated` — a human's manual approximation.
 */
export type AmountBasis = 'actual' | 'forecast' | 'estimated';

export const AMOUNT_BASIS_LABELS: Record<AmountBasis, string> = {
  actual: 'Actual',
  forecast: 'Forecast',
  estimated: 'Estimated',
};

/** Only `actual` amounts may be reported without a qualifier. */
export function requiresQualifier(basis: AmountBasis): boolean {
  return basis !== 'actual';
}

/**
 * The two dates every financial record carries.
 *
 * `effectiveOn` decides which period the record belongs to; `postedAt` records
 * when the system learned about it. Reports are driven by `effectiveOn`; audit
 * and "what did we know when" questions are driven by `postedAt`.
 */
export interface DatedEntry {
  readonly effectiveOn: IsoDate;
  readonly postedAt: IsoDateTime;
}
